#!/bin/sh
set -e

echo "🔧 Initializing schema '${SCHEMA_NAME:-lake}' for user '$POSTGRES_USER' in db '$POSTGRES_DB'"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE SCHEMA IF NOT EXISTS ${SCHEMA_NAME:-lake};

  GRANT USAGE, CREATE ON SCHEMA ${SCHEMA_NAME:-lake} TO ${POSTGRES_USER};
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ${SCHEMA_NAME:-lake} TO ${POSTGRES_USER};
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ${SCHEMA_NAME:-lake} TO ${POSTGRES_USER};

  ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME:-lake}
  GRANT ALL PRIVILEGES ON TABLES TO ${POSTGRES_USER};

  ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME:-lake}
  GRANT ALL PRIVILEGES ON SEQUENCES TO ${POSTGRES_USER};

  ALTER DATABASE ${POSTGRES_DB} SET search_path TO ${SCHEMA_NAME:-lake}, public;
EOSQL
